### ISSUE TITLE
Do not override message in Formalism::NoCoercionError

### ISSUE THREAD

**Issue by JelF** [AlexWayfer/formalism#1]
https://github.com/AlexWayfer/formalism/blob/65c538b29f68fe0b3541d5c26e065b6491933db3/lib/formalism/form/coercion.rb#L77

I think better idea is to use super with this message. Overriding of stdlib method is not bad, but it is a bit worse that not doing so

**Comment by AlexWayfer** [comment]
I agree. Thank you.

**Comment by AlexWayfer** [comment]
Ops, misclick.
